services:
  app:
    build: ./app
    image: rewinteer/pointer:app-1
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_URL=${DB_URL}
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - APP_PASSWORD=${APP_PASSWORD}
    networks:
      - pointer
    ports:
      - "5000:5001"
  db:
    build: ./db
    image: rewinteer/pointer:db-1
    restart: unless-stopped
    volumes:
      - db_data_pointer:/var/lib/postgresql/data
      - ./db/data/pointerAppDb.sql:/docker-entrypoint-initdb.d/pointerAppDb.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      - pointer
volumes:
  db_data_pointer:

networks:
  pointer:
    name: pointer_network
